project:
  type: website
  output-dir: docs

    
  
website:
  page-navigation: true
  title: "Foundations of Data Science"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - href: precalculus.qmd
        text: "Precalculus"
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2026, Judith Canner and CA Learning Lab"
    background: "#D9E3E4"    

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



