---
title: "PreCalculus"
format: 
  live-html:
    webr:
      packages: 
        - tidyverse
      resources: 
        - https://raw.githubusercontent.com/jcanner/foundations-of-data-science/refs/heads/master/courses/data/fish.csv
      cell-options:
        warning: false
        completion: false
execute: 
  warning: false 
  message: false
  echo: true
embed-resources: true
code-copy: true
code-overflow: wrap
toc: true
number-sections: true
css: ../styles.css
---

{{< include ../_extensions/r-wasm/live/_knitr.qmd >}}  

```{webr}
#| label: theme
#| include: false
#| edit: false
library(tidyverse)
theme_set(theme_light())
options(ggplot2.continuous.color = scale_color_viridis_c, 
        ggplot2.continuous.fill = scale_fill_viridis_c,
        ggplot2.discrete.color = scale_color_viridis_d,
        ggplot2.discrete.fill = scale_fill_viridis_d)

fish <- read_csv("fish.csv", show_col_types = FALSE)
```

```{r}
#| label: setup-checkdown
#| include: false
library(readr)
library(ggplot2)
```


## Overview
Precalculus students learn functions as graphs, tables, transformations, and symbolic rules. In data science, functions can be used as models, or simply mathematical descriptions of patterns for real data. The following discussion lesson plan provides instructors guidance on how to connect concepts about functions to data modeling at an introductory level. The goal is to help students see that functions can be used to approximate and describe real world relationships, which is the foundation of machine learning.


## Integrating Data Science into Precalculus
Precalculus provides a foundation in understanding functions, which are the foundations of all machine learning methods - everything is just another linear model in the end.  Therefore, emphasizing aspects of modeling with linear and non-linear functions will build connections between the content and data science and reinforce the need for Precalculus as a foundational course in data science

### Precalculus Content

1. Evaluating functions 
2. Graphs/functions
3. Linear/nonlinear functions
4. Exponential/log functions
5. Interpreting graphs
6. Modeling data.

### Data Science Content

1. Explanatory/response variables
2. Scatterplots
3. Modeling
4. Predictions
5. Interpreting graphs

## Goals
1. Explain how functions can be introduced as models of data.
2. Connect the idea of input/output to explanatory/response variables.
3. Use real data sets (fish data set) to compare different function models.
4. Discuss limitations of using mathematical models for predictions.

## Lesson

In precalculus, we describe a function as a rule that assigns each input exactly one output. In data science, we can view functions as a model. A model is a simplified representation of data that describes patterns and allows us to make predictions. 

In this lesson we will be using the Fish Market Data set. This data set includes seven fish species and measurements such as their weight, length, height, and width. In this activity, students can use the physical features of the fish as input variables to predict a fish’s weight. This could be useful for fishermen, where measuring a fish’s length or width may be easier than weighing it. Students can compare linear and polynomial models to see which better represents the relationship between a fish’s measurements and its weight. 

We can also introduce the idea that real data does not always have perfect linear patterns, such as a fish that may gain weight faster than the length increases. We can then discuss how nonlinear models may be helpful in describing different types of patterns in data. 


## Activity

### Part 1: Which function fits the fish?
Students compare linear, quadratic, power, and exponential models for predicting fish weight from length. Instructors discuss how visual fit, residual plots, and context guide model choice.

Can we estimate the weight of a fish based on its other physical features?

```{webr}
#| edit: false
#| output: false

```

```{ojs}
//| echo: false
viewof input_species = Inputs.select(["Perch", "Bream", "Roach", "Pike", "Smelt", "Parkki", "Whitefish"])

```

```{webr}
#| edit: false
#| echo: false
#| input:
#|  - input_species
fish |> 
  filter(Species == input_species) |> 
  ggplot(mapping = 
           aes(x = Length1, 
               y = Weight)) +
  geom_point() +
  labs(
    title = "Scatterplot of Weight and Length of Fish",
    x = "Length (cm)",
    y = "Weight (grams)"
  )
```

We can begin with only two variables where x = length, and y = weight. We can show students a scatterplot of fish length vs. weight for different species of fish. We can then have a discussion about the plot.

1. What do you notice about the relationship between length and weight?
2. Is the relationship linear? Is it a function?
3. "Does the relationship change depending on species? What do you notice is different?"

### Part 2: Now we can fit a linear model to our scatterplots and discuss what we notice.


```{ojs}
//| echo: false
viewof input_species2 = Inputs.select(["Perch", "Bream", "Roach", "Pike", "Smelt", "Parkki", "Whitefish"])

```

```{webr}
#| edit: false
#| echo: false
#| input:
#|  - input_species2
fish |> 
  filter(Species == input_species2) |> 
  ggplot(mapping = 
           aes(x = Length1, 
               y = Weight)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, formula = y~x)+
  labs(
    title = "Scatterplot of Weight and Length of Fish With Linear Models",
    x = "Length (cm)",
    y = "Weight (grams)"
  )
```

We can then have students examine a linear model and discuss.
1. For what species does the linear model accurately represent?
2. What does the slope mean in the context of the problem?
3. What does the y-intercept mean in the context of the problem?
4. Does the y-intercept make logical sense?
5. Does the line fit the model appropriately?

### Part 3: Next, we will examine polynomial trend lines.


```{ojs}
//| echo: false
viewof input_species3 = Inputs.select(["Perch", "Bream", "Roach", "Pike", "Smelt", "Parkki", "Whitefish"])

```

```{webr}
#| edit: false
#| echo: false
#| input:
#|  - input_species3
fish |> 
  filter(Species == input_species3) |> 
  ggplot(mapping = 
           aes(x = Length1, 
               y = Weight)) +
  geom_point() +
  geom_smooth(method = 'loess', se = FALSE, formula = y~x)+
  labs(
    title = "Scatterplot of Weight and Length of Fish With Linear Models",
    x = "Length (cm)",
    y = "Weight (grams)"
  )
```

Next, we can show students a polynomial trend line and discuss.

1. How does this trend line compare to the linear trend line?
2. Can we predict the length of a fish by using its weight?

### Part 4: Transformed Variables

Students can also explore whether transforming a variable can make the relationship appear more linear. We can create new columns for (Length^2) and (Length^3), and plot the weight against each transformed variable. Students can compare the transformed graphs with the original plot and discuss which model looks more linear.

```{ojs}
//| echo: false
viewof input_species4 = Inputs.select(["Perch", "Bream", "Roach", "Pike", "Smelt", "Parkki", "Whitefish"])

```

:::: {layout="[50, 50]"}

::: {#squared-column}



```{webr}
#| edit: false
#| echo: false
#| input:
#|   - input_species4

fish |>
  filter(Species == input_species4) |>
  mutate(
    Length1_squared = Length1^2
  ) |>
  ggplot(aes(x = Length1_squared, y = Weight)) +
  geom_point() +
  geom_smooth(method = "lm", 
              se = FALSE,
              formula = y ~ poly(x, 2)) +
  labs(
    title = "Weight vs. Length Squared",
    x = "Length² (cm²)",
    y = "Weight (grams)"
  )
```

:::

::: {#squared-column}



```{webr}
#| edit: false
#| echo: false
#| input:
#|   - input_species4

fish |>
  filter(Species == input_species4) |>
  mutate(
    Length1_cubed = Length1^3
  ) |>
  ggplot(aes(x = Length1_cubed, y = Weight)) +
  geom_point() +
  geom_smooth(method = "lm", 
              se = FALSE, 
              formula = y ~ poly(x, 2)) +
  labs(
    title = "Weight vs. Length Cubed",
    x = "Length³ (cm³)",
    y = "Weight (grams)"
  )
```

:::

::::


1. Does plotting weight against (Length^2) or (Length^3) change the pattern?
2. Which graph appears to be the most linear?
3. Does a more linear graph make the predictions easier or more accurate?
4. Take note of which species of fish work well with the two different transformations.



### Activity 2: Domain, range, and model misuse
Students identify the observed range of lengths and predict weights inside and outside that range. They label predictions as interpolation or extrapolation and explain why extrapolation can be misleading.

## Conclusion

After this lesson, students should now understand that functions can model relationships in the real world, and help us make predictions. Linear and quadratic models are simple examples of the types of models that can be used with machine learning. However, not all models are good models and are only approximations, so they may not always be accurate or make sense outside of the context of our data.


## Additional Resources

